In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.decomposition import PCA
import pandas as pd
import numpy as np

data = load_breast_cancer(as_frame=True)
X = data.data
y = data.target

In [6]:
def get_main_comp(X , num_components):
    X_meaned = X - np.mean(X , axis = 0)

    cov_matrix = np.cov(X_meaned , rowvar = False)

    values , vectors = np.linalg.eigh(cov_matrix)

    sorted_index = np.argsort(values)[::-1]
    sorted_value = values[sorted_index]
    sorted_vectors = vectors[:,sorted_index]

    vector_subset = sorted_vectors[:,0:num_components]

    X_reduced = np.dot(vector_subset.transpose() , X_meaned.transpose() ).transpose()
    
    return X_reduced

get_main_comp(X, 2)

array([[1160.1425737 ,  293.91754364],
       [1269.12244319,  -15.63018184],
       [ 995.79388896,  -39.15674324],
       ...,
       [ 314.50175618,  -47.55352518],
       [1124.85811531,  -34.12922497],
       [-771.52762188,   88.64310636]])

In [7]:
def get_main_comp_embedded(X, num_comp):
    pca = PCA(n_components=num_comp)
    XPCAreduced = pca.fit_transform(X)
    return XPCAreduced
print(get_main_comp_embedded(X, 2))

[[1160.1425737  -293.91754364]
 [1269.12244319   15.63018184]
 [ 995.79388896   39.15674324]
 ...
 [ 314.50175618   47.55352518]
 [1124.85811531   34.12922497]
 [-771.52762188  -88.64310636]]


In [8]:
print(get_main_comp(X, 3))

[[1160.1425737   293.91754364   48.57839763]
 [1269.12244319  -15.63018184  -35.39453423]
 [ 995.79388896  -39.15674324   -1.70975298]
 ...
 [ 314.50175618  -47.55352518  -10.44240718]
 [1124.85811531  -34.12922497  -19.74208742]
 [-771.52762188   88.64310636   23.88903189]]


In [10]:
print(get_main_comp_embedded(X, 3))

[[1160.1425737  -293.91754364   48.57839763]
 [1269.12244319   15.63018184  -35.39453423]
 [ 995.79388896   39.15674324   -1.70975298]
 ...
 [ 314.50175618   47.55352518  -10.44240718]
 [1124.85811531   34.12922497  -19.74208742]
 [-771.52762188  -88.64310636   23.88903189]]


In [11]:
print(get_main_comp(X, 4))

[[1160.1425737   293.91754364   48.57839763    8.71197531]
 [1269.12244319  -15.63018184  -35.39453423  -17.86128323]
 [ 995.79388896  -39.15674324   -1.70975298   -4.1993401 ]
 ...
 [ 314.50175618  -47.55352518  -10.44240718    9.77188104]
 [1124.85811531  -34.12922497  -19.74208742   23.66088144]
 [-771.52762188   88.64310636   23.88903189   -2.54724855]]


In [12]:
print(get_main_comp_embedded(X, 4))

[[1160.1425737  -293.91754364   48.57839763   -8.71197531]
 [1269.12244319   15.63018184  -35.39453423   17.86128323]
 [ 995.79388896   39.15674324   -1.70975298    4.1993401 ]
 ...
 [ 314.50175618   47.55352518  -10.44240718   -9.77188104]
 [1124.85811531   34.12922497  -19.74208742  -23.66088144]
 [-771.52762188  -88.64310636   23.88903189    2.54724855]]


In [14]:
print("Пчоти получилось...(((((\nНе знаю, в чем проблема")

Пчоти получилось...(((((
Не знаю, в чем проблема
